language: objective-c
osx_image: xcode8.2
node_js:
  - "6"

before_script:
  - npm install -g swiftx

script:
  - ./scripts/build.sh

after_success:
  - ./scripts/execute-on-packages.sh swiftx update-build-config
  - ./scripts/execute-on-packages.sh swiftx update-dependency-graph
  - ./scripts/execute-on-packages.sh swiftx trigger-downstream-builds

after_failure:
  - ./scripts/execute-on-packages.sh swiftx trigger-downstream-builds --force
